spring.application.name=sudoSolver


spring.datasource.url=jdbc:mysql://localhost:3306/sudoku
spring.datasource.username=root
spring.datasource.password=mysql@2005



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret = G7vK2mQ9xR4pL8zN6wT3yH5cJ1sF0dAaB8uE6nX4qP7rM2kV9
jwt.expiration=86400000